### ISSUE TITLE
Node 14 deprecation warning

### ISSUE THREAD

**Issue by duncdrum** [line-o/gulp-exist-example#5] opened 2021-02-11 10:14 UTC
Fresh checkout (no modifications)

```bash
gulp install
```

=>
```
--- gits/gulp-exist-example ‹main› » gulp clean
[11:10:55] Using gulpfile ~/Documents/gits/gulp-exist-example/gulpfile.js
[11:10:55] Starting 'clean'...
(node:12813) [DEP0097] DeprecationWarning: Using a domain property in MakeCallback is deprecated. Use the async_context variant of MakeCallback or the AsyncResource class instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[11:10:55] Finished 'clean' after 13 ms
```

**Comment by line-o** [comment] 2021-10-07 10:32
@duncdrum could you check if this is still the case? I cannot reproduce it and would close it if you do not object.

**Closed as completed** 2021-10-07 11:51 UTC
